spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:./camunda-h2-database
    driverClassName: org.h2.Driver
    username:

camunda.bpm.admin-user:
  id: demo
  password: demo

server.port: 8070
