spring:
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521:XE
    username: SCOTT
    password: TIGER
    driver-class-name: oracle.jdbc.driver.OracleDriver

camunda.bpm.admin-user:
  id: demo
  password: demo

server.port: 8070
