spring:
  profiles:
    active: local #oracle
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

camunda.bpm.admin-user:
  id: demo
  password: demo

server.port: 8070

camunda:
  bpm:
    database:
      jdbc-batch-processing: false

workflow:
  preprocess:
    # 압축해제 최대 횟수
    extractMaxCnt: 4
    # 전처리 rest api 서버 URL
    serverIp: http://localhost:8070

